<a href="https://colab.research.google.com/github/JogadorZero/Estatistica_Aplicada/blob/main/Amostragem_Estratificada.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import random
import numpy as np

dataset = pd.read_csv('census.csv')

#Amostragem Estratificada

In [2]:
from sklearn.model_selection import StratifiedShuffleSplit

In [3]:
dataset['income'].value_counts()

income
 <=50K    24720
 >50K      7841
Name: count, dtype: int64

#####Calculando a representatividade (%) dessas informações

In [4]:
7841 / len(dataset), 24720 / len(dataset)

(0.2408095574460244, 0.7591904425539756)

In [6]:
split = StratifiedShuffleSplit(test_size=0.1)
for x, y in split.split(dataset, dataset['income']):
  df_x = dataset.iloc[x]
  df_y = dataset.iloc[y]

In [8]:
df_x.shape, df_y.shape

((29304, 15), (3257, 15))

In [9]:
df_y.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
20118,44,Private,304530,Some-college,10,Divorced,Craft-repair,Not-in-family,White,Male,0,0,55,United-States,<=50K
3872,38,Private,170020,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,3137,0,45,United-States,<=50K
12566,44,Private,156413,Some-college,10,Married-civ-spouse,Tech-support,Husband,White,Male,0,0,44,United-States,>50K
457,38,Private,351299,Some-college,10,Married-civ-spouse,Transport-moving,Husband,Black,Male,0,0,50,United-States,<=50K
17281,32,Private,372692,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K

In [10]:
100/len(dataset)

0.0030711587481956942

In [11]:
split = StratifiedShuffleSplit(test_size=0.0030711587481956942)
for x, y in split.split(dataset, dataset['income']):
  df_x = dataset.iloc[x]
  df_y = dataset.iloc[y]

In [12]:
df_x.shape, df_y.shape

((32461, 15), (100, 15))

In [15]:
df_y.head()

,age,workclass,final-weight,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loos,hour-per-week,native-country,income
167,46,State-gov,102628,Masters,14,Widowed,Protective-serv,Unmarried,White,Male,0,0,40,United-States,<=50K
9611,19,Private,232368,Some-college,10,Never-married,Other-service,Own-child,White,Female,0,0,35,United-States,<=50K
14065,38,Private,177121,Some-college,10,Separated,Other-service,Not-in-family,White,Female,0,0,58,United-States,<=50K
16998,39,Self-emp-not-inc,164593,Doctorate,16,Never-married,Prof-specialty,Not-in-family,White,Male,4787,0,40,United-States,>50K
4940,38,Private,207202,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,48,United-States,>50K

In [16]:
df_y['income'].value_counts()

income
 <=50K    76
 >50K     24
Name: count, dtype: int64

In [18]:
def amostragem_estratificada(dataset, percentual):
  split = StratifiedShuffleSplit(test_size=percentual, random_state=1)
  for _, y in split.split(dataset, dataset['income']):
    df_y = dataset.iloc[y]
  return df_y

In [19]:
df_amostra_estratificada = amostragem_estratificada(dataset, 0.0030711587481956942)
df_amostra_estratificada.shape

(100, 15)